#!/bin/bash

echo 'start keycloak...'
echo "\$ KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN} KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD} bin/kc.sh $@"

KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN} KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD} bin/kc.sh "$@"
