#!/bin/bash

DATABASE_NAME=$1
USER_NAME=$2
PASSWORD=$3
OPTION=$4

WITH_OPTION=

# example: WITH mysql_native_password
if [ "${OPTION}" != "" ]; then
    WITH_OPTION="WITH ${OPTION}"
fi

SQL=$(cat <<EOF
CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};

CREATE USER ${USER_NAME}@localhost IDENTIFIED ${WITH_OPTION} BY '${PASSWORD}';
CREATE USER ${USER_NAME}@'%' IDENTIFIED ${WITH_OPTION} BY '${PASSWORD}';

GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO ${USER_NAME}@localhost;
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO ${USER_NAME}@'%';

FLUSH PRIVILEGES;
EOF
)

mysql -uroot -ppassword -h`hostname -i` -e "${SQL}"
