#!/bin/bash

DATABASE_NAME=$1
USER_NAME=$2
PASSWORD=$3

SQL=$(cat <<EOF
CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};

CREATE USER ${USER_NAME}@localhost IDENTIFIED BY '${PASSWORD}';
CREATE USER ${USER_NAME}@'%' IDENTIFIED BY '${PASSWORD}';

GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO ${USER_NAME}@localhost;
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO ${USER_NAME}@'%';

FLUSH PRIVILEGES;
EOF
)

mysql -uroot -e "${SQL}"
